./nexus-client publish value /testing/a 123
./nexus-client publish value /testing/b 456
./nexus-client publish value /testing/c 789
./nexus-client publish value /testing/d 101
./nexus-client publish value /testing/e 102
./nexus-client publish value /testing/f 103
./nexus-client publish value /testing/g 104
./nexus-client publish value /testing/h 105
./nexus-client publish value /testing/i 106
./nexus-client publish value /testing/j 107
./nexus-client publish value /testing/alpha 108
./nexus-client publish value /testing/alpha_beta 109
./nexus-client publish value /testing/alpha_gamma 110
./nexus-client publish value /testing/alphabet 'abc'

./nexus-client publish dataset /testing/dataset/a ./tests/example_a.csv
./nexus-client publish dataset /testing/dataset/b ./tests/example_b.csv
./nexus-client publish dataset /testing/dataset/c ./tests/example_c.csv
./nexus-client publish dataset /testing/dataset/d ./tests/example_d.csv
